name: PR Status Labeller

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - reopened
  pull_request_review:
    types:
      - submitted

jobs:
  pr_status_labeller:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run PR Status Labeller
        run: |
          node auto_update.js
        env:
          UPDATE_LABEL: "ready"
          IGNORED_LABELS: "inprogress"
          MIN_APPROVAL_COUNT: 1
