name: Trigger After Successful Check Suite

on:
  workflow_dispatch:
  check_run:
    types: [completed]
    
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Run payload
        run: echo "${{ github.event.client_payload.message }}"
      
      - name: Check if check runs was successful
        id: check_runs
        run: echo "Check suite status ${{ github.event.check_run.conclusion }}"

      - name: Check if check runs was successful
        id: check_runs_name
        run: echo "Check suite status ${{ github.event.check_run.app.name }}"
      
      - name: Run another action
        run: echo "SUCCESS"
