name: Trigger After Successful Check Suite

on:
  workflow_dispatch:
  check_run:
  #check_suite:
    types: [completed]
    
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run bitrise script
        id: bitris_script
        run: python ${GITHUB_WORKSPACE}/scripts/bitrise-checks.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #PAYLOAD: ${{ github.event.check_run }}
          #PRS: ${{ github.event.check_run.pull_requests }}
          
      - name: Check if check runs payload
        id: check_payload_branch
        run: echo "Check suite status ${{ github.event.check_run }}"

      - name: Check if check runs pulls
        id: check_runs_pull_requests
        run: |
          for pr in ${{ github.event.check_run.pull_requests }}; do
            echo "Pull Request Number: $pr.number"
          done
        
      - name: Check if check runs status
        id: check_runs_status
        run: echo "Check suite status ${{ github.event.check_run.status }}"
        
      - name: Check if check runs conclusion
        id: check_runs
        run: echo "Check suite status ${{ github.event.check_run.conclusion }}"

      - name: Check if check runs app name
        id: check_runs_name
        run: echo "Check suite status ${{ github.event.check_run.app.name }}"
      
      - name: Run another action
        run: echo "SUCCESS"
