name: Trigger After Successful Check Suite

on:
  check_suite:
    types:
      - completed


jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check if check suite was successful
        id: check_status
        run: echo "Check suite status ${{ github.event.check_suite.conclusion }}"

      - name: Trigger if check suite was successful
        if: steps.check_status.outputs.check_status == 'success'
        run: |
          echo "Check suite was successful"
          # Add your custom commands here
