name: Trigger After Successful Check Suite

on:
  workflow_dispatch:
  check_run:
  #check_suite:
    types: [completed]
    
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run bitrise script
        id: bitris_script
        run: |
          echo "CHECK_RUN_CONCLUSION=$GITHUB_EVENT_PATH" >> $GITHUB_ENV
          python .github/bitrise-checks.py

      - name: Check if check runs path
        id: check_path
        run: echo "Event path $GITHUB_EVENT_PATH and env $GITHUB_ENV"
        
      - name: Check if check runs payload
        id: check_payload_branch
        run: echo "Check suite status ${{ github.event.check_run }}"

      - name: Check if check runs pulls
        id: check_runs_pull_requests
        run: |
          for pr in ${{ github.event.check_run.pull_requests }}; do
            echo "Pull Request Number: $pr.number"
          done
        
      - name: Check if check runs status
        id: check_runs_status
        run: echo "Check suite status ${{ github.event.check_run.status }}"
        
      - name: Check if check runs conclusion
        id: check_runs
        run: echo "Check suite status ${{ github.event.check_run.conclusion }}"

      - name: Check if check runs app name
        id: check_runs_name
        run: echo "Check suite status ${{ github.event.check_run.app.name }}"
      
      - name: Run another action
        run: echo "SUCCESS"
