name: Trigger After Successful Check Suite

on:
  workflow_dispatch:
  check_run:
    types: [rerequested, completed]
    
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:

      - name: Run another action
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
