name: Trigger After Successful Check Suite

on:
  workflow_dispatch:
  check_run:
    types: [rerequested, completed]
    
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
        
      - name: Run another action
        run: echo "SUCCESS"
