name: Trigger After Successful Check Suite

on:
  workflow_dispatch:
  check_suite:
    types:
      - completed
    # Add more check suites here
    workflows:
      - Bitrise Checks
      - bitrise-checks


jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check if check_suite successful
        id: check_suite
        run: echo "Check suite status ${{ github.event.check_suite }}"

      - name: Check if check_runs was successful
        id: check_runs
        run: echo "Check suite status ${{ github.event.check_runs }}"
