name: Trigger After Successful Check Suite

on:
  workflow_dispatch:
  check_run:
  #check_suite:
    types: [completed]
    
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:

      - name: Check if check runs branch
        id: check_runs_branch
        run: echo "Check suite status ${{ github.event.check_run.head_branch }}"

      - name: Check if check runs pulls
        id: check_runs_pull_requests
        run: |
          for pr in "${{ github.event.check_run.pull_requests }}"; do
            echo "Pull Request Number: $pr.number"
          done
        
      - name: Check if check runs status
        id: check_runs_status
        run: echo "Check suite status ${{ github.event.check_run.status }}"
        
      - name: Check if check runs conclusion
        id: check_runs
        run: echo "Check suite status ${{ github.event.check_run.conclusion }}"

      - name: Check if check runs app name
        id: check_runs_name
        run: echo "Check suite status ${{ github.event.check_run.app.name }}"
      
      - name: Run another action
        run: echo "SUCCESS"
